[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel",
  "gcc",
  "pkg-config",
  "openssl",
  "libffi",
  "zlib",
  "libxml2",
  "libxslt",
  "postgresql",
  "nodejs_18",
  "npm-9_x"
]

[phases.install]
cmds = [
  "export PATH=$HOME/.local/bin:$PATH",
  "pip install --user --upgrade pip setuptools wheel",
  "pip install --user -r requirements.txt",
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "export PATH=$HOME/.local/bin:$PATH && python web_server.py"