[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "gunicorn web_server:app --bind 0.0.0.0:$PORT --workers 2 --timeout 300"